#!/usr/bin/bash
#
# script to backup the Backdrop Database and Essential Settings
# to a dated folder inside Backups Folder
#
# 2024-10-06 had to fix the MySQL Sandbox problem found here https://mariadb.org/mariadb-dump-file-compatibility-change/
#               and also in my odt file /home/francis/storage/Francis/Computing/Backdrop/MariaDB_Dump_File_Compatibility_Change.odt
#               by removing the first line
#
# 2023-03-04 changed from Brush to Bee
#
# 2022-05-26 changed to Brush from Drush
#
#--------------------------------------------------
fix_db_error() {
  # there must be a parameter passed to this function which is the folder where the database is saved to
  # The FOLDER is $1
  # Unzip the db
  echo 'Checking the first line of the database for the sandbox'
  gunzip "$1/database.sql.gz"
  result=$(head -n1 "$1/database.sql" | grep '999999')
  if [[ $result != '' ]]; then
        echo 'Line Present, so deleting it';
        sed -i '1d' "$1/database.sql"
  fi
  echo 'First line is now:'
  head -n1 "$1/database.sql"
  # Zip it up again
  gzip "$1/database.sql"
  # update git if exporting later
  # git commit -am "Modified Database for first line error"
}
#------------------------------------------------------
cd web || exit
RED='\033[0;31m'
dateStamp=$(eval date +%Y-%m-%d_%H-%M-%S)
if [[ $# -eq 0 ]] ; then
    printf "%s You must give a folder as an argument Not a Path\n" "${RED}"
    printf "%s You should use the name for this site if poss\n" "${RED}"
    exit 1
fi
DIRECTORY=~/Backups/$1/$dateStamp
if [[ -d "${DIRECTORY}" && ! -L "${DIRECTORY}" ]] ; then
    echo "Saving Database and Settings to $DIRECTORY"
else
    echo "Saving Database and Settings to $DIRECTORY"
    mkdir -p "${DIRECTORY}"
fi
bee db-export "${DIRECTORY}/database.sql"
fix_db_error $DIRECTORY
cp se* "${DIRECTORY}"
rsync -arz ../config/active "${DIRECTORY}/"
# Consider other files to backup eg css for the local theme css files
#
echo "Finished"
ls -lh "${DIRECTORY}"

