#!/bin/bash
# 
# script to backup the Backdrop Database and Essential Settings
# to a dated folder inside Backups Folder
#
cd web
RED='\033[0;31m'
NC='\033[0m' # No Color
dateStamp=`eval date +%Y-%m-%d_%H-%M-%S`
if [[ $# -eq 0 ]] ; then
    printf "${RED}You must give a folder as an argument Not a Path\n"
    printf "${RED} You should use the name for this site if poss\n"
    exit 1
fi
DIRECTORY=~/Backups/$1/$dateStamp
if [[ -d "${DIRECTORY}" && ! -L "${DIRECTORY}" ]] ; then
    echo "Saving Database and Settings to $DIRECTORY"
else
    echo "Saving Database and Settings to $DIRECTORY"
    mkdir -p "${DIRECTORY}"
fi
drush sql-dump --gzip --result-file="${DIRECTORY}/database.sql"
cp se* "${DIRECTORY}"
rsync -avrz ../config/active "${DIRECTORY}/"
# Consider other files to backup eg css for the local theme css files
#
echo "Finished"
ls -lh "${DIRECTORY}"
