#!/bin/bash
#
# script to backup the Backdrop Database and Essential Settings
# to a dated folder inside Backups Folder
#
# 2023-03-04 changed from Brush to Bee
#
# 2022-05-26 changed to Brush from Drush
#
cd web || exit
RED='\033[0;31m'
dateStamp=$(eval date +%Y-%m-%d_%H-%M-%S)
if [[ $# -eq 0 ]] ; then
    printf "%s You must give a folder as an argument Not a Path\n" "${RED}"
    printf "%s You should use the name for this site if poss\n" "${RED}"
    exit 1
fi
DIRECTORY=~/Backups/$1/$dateStamp
if [[ -d "${DIRECTORY}" && ! -L "${DIRECTORY}" ]] ; then
    echo "Saving Database and Settings to $DIRECTORY"
else
    echo "Saving Database and Settings to $DIRECTORY"
    mkdir -p "${DIRECTORY}"
fi
# brush sql-dump --gzip --result-file="${DIRECTORY}/database.sql"
bee db-export "${DIRECTORY}/database.sql"
cp se* "${DIRECTORY}"
rsync -arz ../config/active "${DIRECTORY}/"
# Consider other files to backup eg css for the local theme css files
#
echo "Finished"
ls -lh "${DIRECTORY}"
