#!/usr/bin/bash
#
# Script to backup the database and any files you want
# then copy the database to the config folder
#
# 2024-10-06 had to fix the MySQL Sandbox problem found here https://mariadb.org/mariadb-dump-file-compatibility-change/
#               by removing the first line
#
# 2023-03-04 changed to bee from drush
#
# Originally using Drush
# then Export Drupal Settings using Drush 8
#
site_folder() {
  DIR_PATH=$(/usr/bin/pwd)
  IFS='/' read -ra DIR <<< "$DIR_PATH"
  echo "${DIR[-1]}"
} # End of site_folder
#--------------------------------------------------
fix_db_error() {
  # there must be a parameter passed to this function which is the folder where the database is saved to
  # The FOLDER is $1
  # Unzip the db
  echo 'Checking the first line of the database for the sandbox'
  gunzip "$1/database.sql.gz"
  result=$(head -n1 "$1/database.sql" | grep '999999')
  if [[ $result != '' ]]; then
        echo 'Line Present, so deleting it';
        sed -i '1d' "$1/database.sql"
  fi
  echo 'First line is now:'
  head -n1 "$1/database.sql"
  # Zip it up again
  gzip "$1/database.sql"
}
#------------------------------------------------------
echo
echo "Backup the site Database and Settings"
./backupEssentials "$(site_folder)"
echo "Exporting the Settings to config/versioned"
echo
# start with a clean slate
echo "Clearing config/versioned folder and copying config/active"
rm config/versioned/*
cp config/active/* config/versioned/
cd web || exit
echo "Dumping Database to config/versioned folder"
bee db-export ../config/versioned/database.sql
fix_db_error ../config/versioned
echo
echo "Some Settings will transfer this site data eg Title, Branding emails etc"
echo "which we do NOT Want, but the importConfigSync script takes care of this"
echo
echo
echo "Finished - Ready to git commit -am ..... and push"
echo
echo "Then having pushed, on the remote site, "
echo "then git checkout update and git pull origin master"
echo "and then importConfigSync to finish the job"
echo

