#!/bin/bash
#
# Script to overwrite items from system.core.json file with ignored settings
# then Sync the database you choose, then
# Import Backdrop Settings using Drush 8
#
# Backup the site Database and Settings
echo
echo "Backup the site Database and Settings"
./backupEssentials SITEFOLDER
echo
echo "Importing the Settings from config/staging"
echo
rm config/staging/*
cp config/versioned/*.json config/staging/
echo "Removing Unnecessary Settings from system.core.json"
php config/ignoreSettings.php
echo
echo
cd web
echo "Importing the Database"
echo
drush sql-drop -y
drush sql-cli < ../config/versioned/database.sql
echo
echo "Updating Database and Clearing the Cache"
drush updb
drush cc all
echo
echo "Importing the staged config"
echo
drush bcim
echo
echo "Updating Database and Clearing the Cache"
drush updb
drush cc all
echo "Finished - Ready to test the updates"
echo

