#!/bin/bash
#
# Script to overwrite items from system.core.json file with ignored settings
# then Sync the database you choose, then
# Import Backdrop Settings using Drush 8
#
# Backup the site Database and Settings
./backupEssestials SITEFOLDER
echo "Importing the Settings from config/staging"
echo
echo "Removing Unnecessary Settings from system.core.json"
php config/ignoreSettings.php
echo
echo
options=("Local Database" "Dev Database" "Prod Database" "No Database")
echo "Select which Database to import DATABASE"
select opt in "${options[@]}"
do
    case $opt in
        "Local Database")
            echo "Importing the Local Db to DATABASE"
            gunzip config/local_db/database.sql.gz
            mysql --defaults-extra-file=.dbCreds DATABASE < config/local_db/database.sql
            gzip config/local_db/database.sql
            break
            ;;

        "Dev Database")
	    echo "Importing the Dev Db to DATABASE"
	    gunzip config/dev_db/database.sql.gz
	    mysql --defaults-extra-file=.dbCreds DATABASE < config/dev_db/database.sql
	    gzip config/dev_db/database.sql
            break
            ;;
        "Prod Database")
	    echo "Importing the Prod Db to DATABASE"
	    gunzip config/prod_db/database.sql.gz
	    mysql --defaults-extra-file=.dbCreds DATABASE < config/prod_db/database.sql
	    gzip config/prod_db/database.sql
            break
            ;;
        "No Database")
            echo "No Db"
            break
            ;;
    esac
done
cd web
drush updb
drush cc all
drush bcim
echo
drush updb
drush cc all
# stash the unzipped and rezipped database
git stash
echo "Finished - Ready to test the updates"
echo

