#!/usr/bin/bash
#
# Script to overwrite items from system.core.json file with ignored settings
# then Sync the database you choose, then
# Import Backdrop Settings using Drush 8
#
# Backup the site Database and Settings
#
# 2023-03-04 changed from Brush to Bee
#
# 2022-05-26 changed to Brush from Drush
#
site_folder() {
  DIR_PATH=$(/usr/bin/pwd)
  IFS='/' read -ra DIR <<< "$DIR_PATH"
  echo "${DIR[-1]}"
} # End of site_folder
echo
echo "Backup the site Database and Settings"
./backupEssentials "$(site_folder)"
echo
echo "Importing the Settings from config/staging"
echo
rm config/staging/*
cp config/versioned/*.json config/staging/
echo "Removing Unnecessary Settings from system.core.json"
php config/ignoreSettings.php
echo
cd web || exit
echo "Importing the Database"
echo
bee db-import ../config/versioned/database.sql.gz
echo
echo "Importing the staged config"
echo
bee bcim -y
echo
echo "Updating Database and Clearing the Cache"
bee updb -y
bee cc all
echo "Finished - Ready to test the updates"
echo

