#!/bin/bash
#
# script to upgrade Backdrop Core
#
GREEN='\033[0;32m'
iRED='\033[0;31m'
NC='\033[0m' # No Color
askfg(){
  local REPLY
  while true;
    do
        read -p "$1 [Y/n]" REPLY </dev/tty
        # Default is Y
        if [ -z "$REPLY" ]; then
          REPLY=Y
        fi
        # Check if the reply is valid
        case "$REPLY" in
          Y*|y*) return 0 ;;
          N*|n*) return 1 ;;
        esac
    done
}       # End of ask()
# remove any leading and trailing spaces
trimSpaces(){
  shopt -s extglob
  local output=$1
  ### Trim leading whitespaces ###
  output="${output##*( )}"
  ### trim trailing whitespaces  ##
  output="${output%%*( )}"
  shopt -u extglob
  echo "${output}"
} # End of trimSpaces
#----------------------------------------------------
# Backup the site Database and Settings
./exportConfigSync
cd web
# Get the Backdrop Version
IFS=':' read -ra version_array <<< `drush status | grep 'Backdrop version'`
version="${version_array[1]}"
version=$(trimSpaces "${version}")
echo $version
if askfg "Do you really want to Upgrade from Version ${version}. I have already taken a backup" ; then
    echo "OK Here we go"
  else
    exit 1
  fi
echo "Getting latest Release Version of Backdrop"
cd "modules"
echo "Upgrade Core"
yes | drush up core
echo ""
echo "Upgrade Modules"
yes | drush up *
echo ""
drush updb
drush cc all
echo
cd ..
./FixPermissions
ls
echo
echo "Now check the site is running OK, Check Status Report and Logs"
printf "${GREEN}If all is OK, then exportConfigSync and git commit and push\n"
echo
printf "${RED}If it all goes 'Pear Shaped' then you can easily restore the previous version as follows\n"
printf "${NC}	1. Remove the web/core folder and gunzip the core-VERSION to web/core from the current backup"
echo "         Remember to be in the web folder before running gunzip"
echo "	2. Clear the contents of the config/staged folder"
echo "	3. Copy the contents of the ~/Backup/WEB-FOLDER/DATE-STAMP/active folder to the config/staged folder"
echo "	4. Run the importConfigSync script"
echo
echo "And that should be that, back where you started"
echo
